### PR TITLE
Fix build error with syntect 4.7.0

### LINKED ISSUE #1991: v0.18.3 not building with Rust 1.57 on Linux x64
**Describe the bug you encountered:**

Not able to build version 0.18.3 using `cargo install bat` on Rust 1.57.0, `x86_64-unknown-linux-gnu`. (Originally encountered when trying to install `cargo-expand`, but this happens when trying to install just `bat` as well.)

```sh
❯ cargo install bat
...
error[E0599]: no method named `add_from_folder` found for struct `ThemeSet` in the current scope
  --> /home/yami/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/assets.rs:59:33
   |
59 |             let res = theme_set.add_from_folder(&theme_dir);
   |                                 ^^^^^^^^^^^^^^^ method not found in `ThemeSet`

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `bat v0.18.3`, intermediate artifacts can be found at `/tmp/cargo-installpeRs2H`

Caused by:
  could not compile `bat` due to previous error
```

**What did you expect to happen instead?**

`bat` builds without error.

**How did you install `bat`?**

```sh
cargo install bat
```

---

**bat version and environment**

```sh
❯ rustc -Vv   
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by taiki-e**
Fixes #1991

### CODE REVIEW

File: Cargo.toml [hunk 1]
```diff
@@ -72,9 +72,9 @@ optional = true
 default-features = false
 
 [dependencies.syntect]
-version = "4.6.0"
+version = "4.7.0"
 default-features = false
-features = ["parsing"]
+features = ["parsing", "plist-load", "dump-load"]
```
Comment (taiki-e) [inline Cargo.toml:77]: If the `dump-load` (or `dump-load-rs`) feature is not specified, the following error is happen. It seems another bug of syntect.

```text
error[E0425]: cannot find function `from_reader` in module `crate::dumps`
   --> /Users/taiki/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.7.0/src/parsing/syntax_set.rs:432:23
    |
432 |         crate::dumps::from_reader(data).expect("data is not corrupt or out of sync with the code")
    |                       ^^^^^^^^^^^ not found in `crate::dumps`
    |
help: consider importing one of these items
    |
1   | use plist::from_reader;
    |
1   | use serde_json::from_reader;
    |

For more information about this error, try `rustc --explain E0425`.
```

Comment (taiki-e) [reply Cargo.toml:77]: Ah, this seems to be a breaking change introduced in https://github.com/trishume/syntect/pull/393.

https://github.com/trishume/syntect/blob/b4e2cbb280c79cc5a3b3c12f342d6b792f905001/Cargo.toml#L62-L64

> ```toml
> # If you enable "parsing", you must also enable either "dump-load" or
> # "dump-load-rs", and "dump-create" or "dump-create-rs". Otherwise the code that
> # enables lazy-loading of syntaxes will not compile.
> ```

**Comment by taiki-e** [comment]
It seems tests are failing due to OOM.

https://github.com/sharkdp/bat/runs/4636833103?check_suite_focus=true

```text
running 44 tests
test assets::build_assets::acknowledgements::tests::test_append_to_acknowledgements_adds_newline_if_missing ... ok
test assets::build_assets::acknowledgements::tests::test_normalize_license_text ... ok
test assets::build_assets::acknowledgements::tests::test_normalize_license_text_with_windows_line_endings ... ok
memory allocation of 7881122326526296064 bytes failederror: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/home/runner/work/bat/bat/target/debug/deps/bat-5f7ebdce0ebb4f19` (signal: 6, SIGABRT: process abort signal)
```

**Comment by taiki-e** [comment]
closing -- syntect 4.7.0 has been yanked: https://github.com/trishume/syntect/issues/402#issuecomment-1001211120

**Comment by sharkdp** [comment]
Thank you anyway for taking a stab at this!
